version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: chess-training-api
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./data:/app/data
      - ./configs:/app/configs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chess-network
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: chess-training-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chess-network
    restart: unless-stopped

networks:
  chess-network:
    driver: bridge

volumes:
  checkpoints:
  logs:
  data:
